

# Load API key from Streamlit secrets
OPENAI_API_KEY ="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"
